### ISSUE TITLE
Nova v3: simplesquid/nova-advanced-number-field v1.1.1 requires laravel/nova ^2.1 -> satisfiable by laravel/nova[2.x-dev]

### ISSUE THREAD

**Issue by oleksandr-roskovynskyi** [simplesquid/nova-advanced-number-field#5]
Problem 1
    - simplesquid/nova-advanced-number-field v1.1.1 requires laravel/nova ^2.1 -> satisfiable by laravel/nova[2.x-dev].
    - simplesquid/nova-advanced-number-field v1.1.0 requires laravel/nova ^2.0 -> satisfiable by laravel/nova[2.x-dev].
    - simplesquid/nova-advanced-number-field v1.1.1 requires laravel/nova ^2.1 -> satisfiable by laravel/nova[2.x-dev].
    - Can only install one of: laravel/nova[3.x-dev, 2.x-dev].
    - Installation request for laravel/nova ~3.0 -> satisfiable by laravel/nova[3.x-dev].
    - Installation request for simplesquid/nova-advanced-number-field ^1.1 -> satisfiable by simplesquid/nova-advanced-number-field[v1.1.0, v1.1.1].

**Comment by mdpoulter** [comment]
#7 fixes this. Thanks
